const mongoose = require('mongoose');
const { Employee, Role, Status } = require('../models/Employee');
const BrokerAdmin = require('../models/BrokerAdmin');
require('dotenv').config();

const connectDB = async () => {
    try {
        const uri = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/fct-dcip-local';
        await mongoose.connect(uri);
        console.log('✅ Connected to MongoDB!');
    } catch (error) {
        console.error('❌ MongoDB connection failed:', error);
        process.exit(1);
    }
};

const createBrokerAdmins = async () => {
    try {
        console.log('🚀 Creating Broker Admins');
        console.log('===============================\n');

        await connectDB();

        // Get required roles and statuses
        let brokerRole = await Role.findOne({ role: 'Broker-Admin' });
        let activeStatus = await Status.findOne({ status: 'Active' });

        if (!brokerRole) {
            console.log('Creating Broker-Admin role...');
            brokerRole = await Role.create({ role: 'Broker-Admin' });
        }

        if (!activeStatus) {
            console.log('Creating Active status...');
            activeStatus = await Status.create({ status: 'Active' });
        }

        const brokerAdmins = [
            {
                firstname: 'Michael',
                lastname: 'Johnson',
                email: 'michael.johnson@premiumbrokers.ng',
                phonenumber: '+2348011111111',
                brokerFirmName: 'Premium Insurance Brokers Ltd',
                brokerFirmLicense: 'BFL-2024-001',
                licenseNumber: 'BRK-001-2024',
                department: 'Claims Management',
                position: 'Senior Broker Administrator'
            },
            {
                firstname: 'Sarah',
                lastname: 'Williams',
                email: 'sarah.williams@elitebrokers.ng',
                phonenumber: '+2348022222222',
                brokerFirmName: 'Elite Insurance Brokers',
                brokerFirmLicense: 'BFL-2024-002',
                licenseNumber: 'BRK-002-2024',
                department: 'Claims Processing',
                position: 'Broker Administrator'
            },
            {
                firstname: 'Daniel',
                lastname: 'Martinez',
                email: 'daniel.martinez@trustbrokers.ng',
                phonenumber: '+2348033333333',
                brokerFirmName: 'Trust Insurance Brokers',
                brokerFirmLicense: 'BFL-2024-003',
                licenseNumber: 'BRK-003-2024',
                department: 'Claims Management',
                position: 'Lead Broker Administrator'
            },
            {
                firstname: 'Jennifer',
                lastname: 'Garcia',
                email: 'jennifer.garcia@reliablebrokers.ng',
                phonenumber: '+2348044444444',
                brokerFirmName: 'Reliable Insurance Brokers Ltd',
                brokerFirmLicense: 'BFL-2024-004',
                licenseNumber: 'BRK-004-2024',
                department: 'Claims Operations',
                position: 'Broker Administrator'
            },
            {
                firstname: 'Christopher',
                lastname: 'Rodriguez',
                email: 'chris.rodriguez@firstchoicebrokers.ng',
                phonenumber: '+2348055555555',
                brokerFirmName: 'First Choice Insurance Brokers',
                brokerFirmLicense: 'BFL-2024-005',
                licenseNumber: 'BRK-005-2024',
                department: 'Claims Management',
                position: 'Broker Administrator'
            }
        ];

        for (const brokerData of brokerAdmins) {
            try {
                // Check if employee already exists
                const existingEmployee = await Employee.findOne({ email: brokerData.email });
                if (existingEmployee) {
                    console.log(`⚠️  Employee ${brokerData.email} already exists, skipping...`);
                    continue;
                }

                // Create employee record with Broker organization
                // Note: Password will be auto-generated from ObjectId by pre-save hook
                const employee = new Employee({
                    firstname: brokerData.firstname,
                    lastname: brokerData.lastname,
                    email: brokerData.email,
                    phonenumber: brokerData.phonenumber,
                    employeeRole: brokerRole._id,
                    employeeStatus: activeStatus._id,
                    organization: 'Broker'
                });

                await employee.save();

                // The password is now the employee's ObjectId (auto-generated by pre-save hook)
                console.log(`   Password: ${employee._id.toString()}`);

                // Create broker admin profile
                const brokerAdmin = new BrokerAdmin({
                    userId: employee._id,
                    organization: 'Broker',
                    brokerFirmName: brokerData.brokerFirmName,
                    brokerFirmLicense: brokerData.brokerFirmLicense,
                    permissions: {
                        canViewClaims: true,
                        canUpdateClaimStatus: true,
                        canViewReports: true,
                        canAccessAnalytics: true
                    },
                    profile: {
                        department: brokerData.department,
                        position: brokerData.position,
                        licenseNumber: brokerData.licenseNumber
                    },
                    settings: {
                        notifications: {
                            email: true,
                            sms: false
                        },
                        dashboard: {
                            defaultView: 'claims',
                            autoRefresh: true
                        }
                    },
                    status: 'active'
                });

                await brokerAdmin.save();

                console.log(`✅ Created broker admin: ${brokerData.firstname} ${brokerData.lastname} (${brokerData.email})`);
                console.log(`   Firm: ${brokerData.brokerFirmName}`);
                console.log(`   License: ${brokerData.brokerFirmLicense}`);

                // Send credentials email
                const { sendBrokerAdminCredentials } = require('../services/emailService');
                const emailResult = await sendBrokerAdminCredentials({
                    email: employee.email,
                    firstname: employee.firstname,
                    lastname: employee.lastname,
                    password: employee._id.toString(),
                    brokerFirmName: brokerData.brokerFirmName,
                    brokerFirmLicense: brokerData.brokerFirmLicense
                });

                if (emailResult.success) {
                    console.log(`   📧 Email sent! Preview: ${emailResult.previewUrl}`);
                } else {
                    console.log(`   ⚠️  Email failed: ${emailResult.error}`);
                }
            } catch (error) {
                console.error(`❌ Failed to create broker admin ${brokerData.email}:`, error.message);
            }
        }

        console.log('\n🎉 Broker Admins creation completed!');
        console.log('==============================\n');

        // Display summary
        const totalBrokerAdmins = await BrokerAdmin.countDocuments({ status: 'active' });
        const totalBrokerEmployees = await Employee.countDocuments({ organization: 'Broker' });

        console.log(`📊 Summary:`);
        console.log(`   - Total Broker Admin profiles: ${totalBrokerAdmins}`);
        console.log(`   - Total Broker employees: ${totalBrokerEmployees}`);
        console.log(`\n📝 Login Credentials:`);
        console.log(`   Email: Any of the emails above`);
        console.log(`   Password: Use the ObjectId shown above for each user`);
        console.log(`   Login URL: /broker-admin/login`);
        console.log(`\n⚠️  Note: The password for each broker admin is their MongoDB ObjectId`);

        await mongoose.connection.close();
        console.log('\n🔌 Database connection closed.');

    } catch (error) {
        console.error('❌ Error creating broker admins:', error);
        process.exit(1);
    }
};

createBrokerAdmins();
